### ISSUE TITLE
Roadmap to deployment

### ISSUE THREAD

**Issue by chrispap95** [chrispap95/hcaloms#1]
This issue is created mostly to organize my thoughts/tasks. The following need to be completed in order to consider this "deployed":

- [x] Remove explicit .par files. Make them generated automatically. Remove passwords from txt files other than the `envSetup.sh` script.
- [x] Scripts should have a `--dryRun` option for testing.
- [x] `uploadAllPedRuns.sh` is completed and working.
- [x] `updatePedRuns.sh` is completed and working.
- [x] `uploadAllLocalRuns.sh` is completed and working.
- [x] `updateLocalRuns.sh` is completed and working.
- [ ] restructure repository to have `production`, `integration`, `dev` branches. *Leave that as a to-do task*

**Comment by chrispap95** [comment]
- [ ] restructure repository to have `production`, `integration`, `dev` branches.

**Comment by chrispap95** [comment]
Still need to smooth out some rough corners in the vcs branches.
